"""adiciona tabela de emails enviados

Revision ID: e12c0a700f4a
Revises: 
Create Date: 2026-10-05 22:41:27.287625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12c0a700f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=64), nullable=False),
    sa.Column('destinatarios', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails_enviados')
    # ### end Alembic commands ###
